const PREFIX = "home";

export const REQUEST_DRAWER_DETAILS = `${PREFIX}REQUEST_DRAWER_DETAILS`;
export const RECEIVE_DRAWER_DETAILS = `${PREFIX}RECEIVE_DRAWER_DETAILS`;

export const REQUEST_SWITCH_CHANGE = `${PREFIX}REQUEST_SWITCH_CHANGE`;
export const RECEIVE_SWITCH_CHANGE = `${PREFIX}RECEIVE_SWITCH_CHANGE`;

export const REQUEST_USER_LOGIN = `${PREFIX}REQUEST_USER_LOGIN`;
export const RECEIVE_USER_LOGIN = `${PREFIX}RECEIVE_USER_LOGIN`;

export const REQUEST_USER_LOGOUT = `${PREFIX}REQUEST_USER_LOGOUT`;
export const RECEIVE_USER_LOGOUT = `${PREFIX}RECEIVE_USER_LOGOUT`;

export const REQUEST_TRAINER_INQUIRY_CHANGE = `${PREFIX}REQUEST_TRAINER_INQUIRY_CHANGE`;
export const RECEIVE_TRAINER_INQUIRY_CHANGE = `${PREFIX}RECEIVE_TRAINER_INQUIRY_CHANGE`;

export const REQUEST_MEMBER_INQUIRY_CHANGE = `${PREFIX}REQUEST_MEMBER_INQUIRY_CHANGE`;
export const RECEIVE_MEMBER_INQUIRY_CHANGE = `${PREFIX}RECEIVE_MEMBER_INQUIRY_CHANGE`;

