const PREFIX = "layout";

export const REQUEST_TOGGLE_CHANGE= `${PREFIX}REQUEST_TOGGLE_CHANGE`;
export const RECEIVE_TOGGLE_CHANGE = `${PREFIX}RECEIVE_TOGGLE_CHANGE`;

export const REQUEST_SIDEMENU_CHANGE= `${PREFIX}REQUEST_SIDEMENU_CHANGE`;
export const RECEIVE_SIDEMENU_CHANGE = `${PREFIX}RECEIVE_SIDEMENU_CHANGE`;

export const REQUEST_USER_ACCESSTOKEN= `${PREFIX}REQUEST_USER_ACCESSTOKEN`;
export const RECEIVE_USER_ACCESSTOKEN = `${PREFIX}RECEIVE_USER_ACCESSTOKEN`;
