const PREFIX = "gym";

export const REQUEST_MEMBER_REGISTRATION = `${PREFIX}REQUEST_MEMBER_REGISTRATION`;
export const RECEIVE_MEMBER_REGISTRATION = `${PREFIX}RECEIVE_MEMBER_REGISTRATION`;

export const REQUEST_PACKAGE_DETAILS = `${PREFIX}REQUEST_PACKAGE_DETAILS`;
export const RECEIVE_PACKAGE_DETAILS = `${PREFIX}RECEIVE_PACKAGE_DETAILS`;

export const REQUEST_SINGLE_MEMBER = `${PREFIX}REQUEST_SINGLE_MEMBER`;
export const RECEIVE_SINGLE_MEMBER = `${PREFIX}RECEIVE_SINGLE_MEMBER`;

export const REQUEST_MEMBER_UPDATE= `${PREFIX}REQUEST_MEMBER_UPDATE`;
export const RECEIVE_MEMBER_UPDATE = `${PREFIX}RECEIVE_MEMBER_UPDATE`;

export const REQUEST_SUBSCRIPTION_DETAILS = `${PREFIX}REQUEST_SUBSCRIPTION_DETAILS`;
export const RECEIVE_SUBSCRIPTION_DETAILS = `${PREFIX}RECEIVE_SUBSCRIPTION_DETAILS`;

export const REQUEST_ISINTEREST_CHANGE = `${PREFIX}REQUEST_ISINTEREST_CHANGE`;
export const RECEIVE_ISINTEREST_CHANGE = `${PREFIX}RECEIVE_ISINTEREST_CHANGE`;

export const REQUEST_ISNOTIFIED_CHANGE = `${PREFIX}REQUEST_ISNOTIFIED_CHANGE`;
export const RECEIVE_ISNOTIFIED_CHANGE = `${PREFIX}RECEIVE_ISNOTIFIED_CHANGE`;

export const REQUEST_REMARKS_CHANGE = `${PREFIX}REQUEST_REMARKS_CHANGE`;
export const RECEIVE_REMARKS_CHANGE = `${PREFIX}RECEIVE_REMARKS_CHANGE`;

export const REQUEST_ENQUIRY_DETAILS = `${PREFIX}REQUEST_ENQUIRY_DETAILS`;
export const RECEIVE_ENQUIRY_DETAILS = `${PREFIX}RECEIVE_ENQUIRY_DETAILS`;

export const REQUEST_ISINTEREST_ENQUIRY_CHANGE = `${PREFIX}REQUEST_ISINTEREST_ENQUIRY_CHANGE`;
export const RECEIVE_ISINTEREST_ENQUIRY_CHANGE = `${PREFIX}RECEIVE_ISINTEREST_ENQUIRY_CHANGE`;

export const REQUEST_ISNOTIFIED_ENQUIRY_CHANGE = `${PREFIX}REQUEST_ISNOTIFIED_ENQUIRY_CHANGE`;
export const RECEIVE_ISNOTIFIED_ENQUIRY_CHANGE = `${PREFIX}RECEIVE_ISNOTIFIED_ENQUIRY_CHANGE`;

export const REQUEST_REMARKS_ENQUIRY_CHANGE = `${PREFIX}REQUEST_REMARKS_ENQUIRY_CHANGE`;
export const RECEIVE_REMARKS_ENQUIRY_CHANGE = `${PREFIX}RECEIVE_REMARKS_ENQUIRY_CHANGE`;

export const REQUEST_BRANCH_DETAILS = `${PREFIX}REQUEST_BRANCH_DETAILS`;
export const RECEIVE_BRANCH_DETAILS = `${PREFIX}RECEIVE_BRANCH_DETAILS`;
